language: python

os:
  - linux

python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install python-opencv
  - sudo dpkg -L python-opencv
  - export PYTHONPATH=/usr/lib/pyshared/python2.7:$PYTHONPATH
  - sudo apt-get install python-numpy
  - sudo apt-get install python-matplotlib

script:
  - python python/unittests/main.py

notifications:
  email: false
