language: python
os:
  - osx
python:
  - "2.7"
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
#script: nosetests

script:
  - python python/unittest.py

notifications:
  email: false
